import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:4242/');
  await page.getByRole('textbox', { name: 'Destination' }).click();
  await page.getByRole('textbox', { name: 'Destination' }).fill('Singapore,');
  await page.getByText('Singapore, Singapore', { exact: true }).click();
  await page.getByRole('button', { name: 'View Booking' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('button', { name: '+' }).nth(1).click();
  await page.getByRole('button', { name: '+ Add Room' }).click();
  await page.getByRole('button', { name: '+' }).nth(2).click();
  await page.getByRole('textbox', { name: 'Destination' }).click();
  await page.getByRole('textbox', { name: 'Destination' }).fill('Singapore,');
  await page.getByText('Singapore, Singapore', { exact: true }).click();
  await page.getByRole('button', { name: 'Search Hotels' }).click();
  await page.getByRole('link', { name: 'Holiday Inn Express Singapore' }).click();
  await page.getByRole('button', { name: '›' }).dblclick();
  await page.getByRole('button', { name: '›' }).click();
  await page.getByRole('button', { name: '›' }).click();
  await page.getByRole('button', { name: '›' }).click();
  await page.getByRole('button', { name: '›' }).click();
  await page.getByRole('button', { name: '›' }).click();
  await page.getByRole('button', { name: '›' }).click();
  await page.getByRole('button', { name: '›' }).click();
  await page.getByRole('button', { name: '›' }).click();
  await page.getByRole('button', { name: '‹' }).click();
  await page.getByRole('button', { name: '‹' }).click();
  await page.getByRole('button', { name: 'View on Map' }).click();
  await page.getByRole('button', { name: 'See Room Options' }).click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('vernicekah@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Hello1234');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Confirm Booking' }).click();
  await page.getByRole('button', { name: 'Proceed to Payment' }).click();
  await page.locator('.__PrivateStripeElement').first().click();
});